-- Supabase SQL Editor에 이 파일 전체를 붙여넣고 Run 하세요.

create table if not exists public.vacations (
  id bigint generated by default as identity primary key,
  title text not null,
  start date not null,
  "end" date not null
);

alter table public.vacations enable row level security;

drop policy if exists "public can read vacations" on public.vacations;
create policy "public can read vacations"
on public.vacations for select
to anon
using (true);

drop policy if exists "public can insert vacations" on public.vacations;
create policy "public can insert vacations"
on public.vacations for insert
to anon
with check (true);

drop policy if exists "public can delete vacations" on public.vacations;
create policy "public can delete vacations"
on public.vacations for delete
to anon
using (true);

-- 기존 화면에 있던 예시 휴가 2개
insert into public.vacations (title, start, "end")
select '오호광 휴가', '2026-09-10', '2026-09-12'
where not exists (
  select 1 from public.vacations where title = '오호광 휴가'
);

insert into public.vacations (title, start, "end")
select '김혜숙 연차', '2026-09-15', '2026-09-15'
where not exists (
  select 1 from public.vacations where title = '김혜숙 연차'
);
